server:
  port: 8884
spring:
  application:
    name: service-zuul
  datasource:
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/bootdo?useUnicode=true&characterEncoding=UTF-8
  thymeleaf:
      mode: LEGACYHTML5
      cache: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  redis缓存的配置
  redis:
    port: 6379
    database: 0   #通常Redis默认使用0号数据库，默认共有16个数据库
    password:
    host: 127.0.0.1
    jedis:
      pool:
         max-active: 8   #最大连接数
         max-wait: -1    #最大阻塞等待时间（负值表示没有限制）
         min-idle: 0    #最大空闲连接
         max-idle: 8    #最大空闲连接
      timeout: 0
#  data:
#    mongodb:
#      host: localhost
#      uri: mongodb://localhost/test
mybatis:
  type-aliases-package: com.xyxz.serviceuser.model
  mapper-locations: classpath:mapper/*.xml
