server:
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: X-Forwarded-Port
  port: 8884
  use-forward-headers: true
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: image/png,image/jpeg,image/jpg,application/json,application/xml,text/html,text/css,text/plain,application/javascript
spring:
  application:
    name: service-zuul
  datasource:
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/zxblog?useUnicode=true&characterEncoding=UTF-8
  thymeleaf:
      mode: LEGACYHTML5
      cache: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  redis缓存的配置
  redis:
    port: 6379
    database: 0   #通常Redis默认使用0号数据库，默认共有16个数据库
    password:
    host: 127.0.0.1
    jedis:
      pool:
         max-active: 8   #最大连接数
         max-wait: -1    #最大阻塞等待时间（负值表示没有限制）
         min-idle: 0    #最大空闲连接
         max-idle: 8    #最大空闲连接
      timeout: 0
  data:
    mongodb:
      host: localhost
      uri: mongodb://localhost/zxlog
mybatis:
  type-aliases-package: com.xyxz.serviceuser.model
  mapper-locations: classpath:mapper/*.xml

github:
  client:
    clientId: 71569962aff4670e996a
    clientSecret: d21bf1e4a35a081703ee991fe7331b62d943b0a6
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
    callback: http://localhost:8884/login/github/callback
    registered-redirect-uri: http://localhost:8884/login/github/callback
    use-current-uri: false
  resource:
    userInfoUri: https://api.github.com/user
